CREATE TABLE `xortify_log` (
  `lid` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `uid` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `uname` varchar(64) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `ip4` varchar(15) NOT NULL DEFAULT '0.0.0.0',
  `ip6` varchar(128) NOT NULL DEFAULT '0:0:0:0:0:0',
  `proxy-ip4` varchar(64) NOT NULL DEFAULT '0.0.0.0',
  `proxy-ip6` varchar(128) NOT NULL DEFAULT '0:0:0:0:0:0',
  `network-addy` varchar(255) NOT NULL DEFAULT '',
  `provider` varchar(128) NOT NULL DEFAULT '',
  `agent` varchar(255) NOT NULL DEFAULT '',
  `extra` text,
  `date` int(12) NOT NULL DEFAULT '0',
  `action` enum('banned','blocked','monitored') NOT NULL DEFAULT 'monitored',
  PRIMARY KEY (`lid`),
  KEY `uid` (`uid`),
  KEY `ip` (`ip4`,`ip6`(16),`proxy-ip4`,`proxy-ip6`(16)),
  KEY `provider` (`provider`(15)),
  KEY `date` (`date`),
  KEY `action` (`action`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;